
services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    ports:
      - "53:53/udp"
      - "953/tcp"
    networks:
      - tamires

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - portal
    networks:
      - tamires




  portal:
    image: wordpress:latest
    restart: always
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db_asa_user
      WORDPRESS_DB_PASSWORD: db_asa_pass
      WORDPRESS_DB_NAME: db_wordpress
    networks:
      - tamires
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: db_wordpress
      MYSQL_USER: db_asa_user
      MYSQL_PASSWORD: db_asa_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    
    networks:
      - tamires
    volumes:
      - db:/var/lib/mysql
   

networks:
  tamires:
    driver: bridge

volumes:
  wordpress:
  db:

